### PR TITLE
Lazy load function addition (compatible with IntersectionObserver API…

### PR DESCRIPTION
**Pull request by eehondas**
Lazy load function addition (compatible with IntersectionObserver API libraries)

### CODE REVIEW

**Comment by passchn** [comment]
What is the point of your addition? I see no difference to the `WebpPicture` method above.

**Comment by eehondas** [comment]
That’s because there is no difference in the function, I added an extra function to take advantage of the lazy loading libraries.

**Comment by passchn** [comment]
But you just copied the method and gave it another name. Why can't you achieve your result with the existing method?

**Comment by eehondas** [comment]
Because it requires the presence of data-src attributes instead of the normal src attributes. Anyway dude I’m revoking this request cause clearly you are polemic about it

**Comment by passchn** [comment]
ok, I did not notice the `data-src` on the `img` tag. Anyway, I'm working on a more flexible API. Look here at the develop branch: https://github.com/jbennecker/silverstripe-webp/blob/develop/src/Picture.php

**Pull request closed without merging**
